## LDA specific settings (also used by LMTP)

# Hostname to use in various parts of sent mails and in LMTP replies.
# Set at init time via HOSTNAME env var.
hostname =

# Address to use when sending rejection mails.
postmaster_address =

# Delimiter character between local-part and detail in email address.
recipient_delimiter = +

# Should saving a mail to a nonexistent mailbox automatically create it?
lda_mailbox_autocreate = no

# Should automatically created mailboxes be also automatically subscribed?
lda_mailbox_autosubscribe = no

protocol lda {
  # Space separated list of plugins to load (default is global mail_plugins).
  mail_plugins = $mail_plugins
}
