protocol imap {
  # Space separated list of plugins to load (default is global mail_plugins).
  mail_plugins = imap_sieve

  # Maximum number of IMAP connections allowed per IP address.
  mail_max_userip_connections = 10
}
